import {
  CompetencyDisplay,
  CompetencyIconWithBackground,
  IndicatorGradeProgress,
} from "@/components/custom/Indicator";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  competenciesWithIncidactors,
  Competency,
  CompetencyWithIndicators,
  Feedback,
  Indicator,
} from "@/lib/types";
import { jsonToMarkdown } from "@/lib/utils";
import { ArrowLeft, ArrowRight, Copy } from "lucide-react";
import {
  createContext,
  PropsWithChildren,
  useCallback,
  useContext,
  useMemo,
  useState,
} from "react";
import Markdown from "react-markdown";
import { toast } from "sonner";

type FeedbackContextType = {
  competenciesWithIncidactors: CompetencyWithIndicators[];
  addFeedback: (
    competency: Competency,
    indicator: string,
    feedback: Feedback,
  ) => void;
  showFeedback: (indicator?: Indicator) => void;
};

const FeedbackContext = createContext<FeedbackContextType>({
  competenciesWithIncidactors: competenciesWithIncidactors,
  addFeedback: () => undefined,
  showFeedback: () => undefined,
});

export function FeedbackProvider(props: PropsWithChildren) {
  const [state, setState] = useState(competenciesWithIncidactors);
  const [selectedFeedback, setSelectedFeedback] = useState<Indicator>();

  const selectedCompetency = useMemo(() => {
    if (!selectedFeedback) return;

    return competenciesWithIncidactors.find(({ indicators }) =>
      indicators.map(({ name }) => name).includes(selectedFeedback.name),
    )?.name;
  }, [selectedFeedback, state]);

  const addFeedback = useCallback(
    (competency: Competency, indicator: string, feedback: Feedback) => {
      setState((prev) => {
        const competencyIndex = prev.findIndex((c) => c.name === competency);
        if (competencyIndex < 0) return prev;

        const next = [...prev];
        const indicatorIndex = next[competencyIndex].indicators.findIndex(
          (i) => i.name === indicator,
        );
        if (indicatorIndex < 0) return prev;

        next[competencyIndex].indicators[indicatorIndex].feedback = feedback;
        return next;
      });
    },
    [],
  );

  const showFeedback = useCallback((indicator?: Indicator) => {
    setSelectedFeedback(indicator);
  }, []);

  return (
    <FeedbackContext.Provider
      value={{
        competenciesWithIncidactors: state,
        addFeedback,
        showFeedback,
      }}
    >
      {props.children}
      {selectedFeedback && selectedCompetency && (
        <FeedbackDialog
          competency={selectedCompetency}
          indicator={selectedFeedback}
        />
      )}
    </FeedbackContext.Provider>
  );
}

export function useFeedback() {
  return useContext(FeedbackContext);
}

const disclaimer = `
The feedback below is generated by a Large Langiage Model (LLM) and is
inherently flawed. The feedback is meant as an initial starting point
for your reflection, please refer to the teaching staff for proper
feedback and guidance.
`;

function FeedbackDialog(props: {
  competency: Competency;
  indicator: Indicator;
}) {
  const { showFeedback } = useFeedback();
  const mardownFeedback = useMemo(() => {
    return jsonToMarkdown(props.indicator.feedback);
  }, [props.indicator.feedback]);

  return (
    <Dialog
      defaultOpen
      onOpenChange={(open) => {
        if (!open) showFeedback();
      }}
    >
      <DialogContent className="max-w-4xl">
        <DialogHeader>
          <DialogTitle className="flex space-x-4">
            <CompetencyIconWithBackground competency={props.competency} />
            <div className="flex flex-col justify-between">
              <CompetencyDisplay
                competency={props.competency}
                className="text-xl"
              />
              <span className="text-sm font-light text-muted-foreground">
                {props.indicator.name}
              </span>
            </div>
          </DialogTitle>
        </DialogHeader>
        <DialogDescription>{disclaimer}</DialogDescription>
        <section className="flex space-x-8">
          <IndicatorGradeProgress grade={props.indicator.feedback?.grade} />
          <ScrollArea className="max-h-[55vh] grow">
            <Button
              variant="outline"
              size="icon"
              className="absolute right-0 top-0"
              onClick={() => {
                navigator.clipboard.writeText(`
========================
⚠️ Disclaimer ⚠️
${disclaimer}
========================

Feedback generated on 31/03/1994 23:04 using ollama3

------------------------
${props.competency.replaceAll("-", " ")} - ${props.indicator.name}
------------------------

${mardownFeedback}`);
                toast.success("Feedback copied to clipboard");
              }}
            >
              <Copy />
            </Button>
            {/* {JSON.stringify(indicator.feedback)} */}
            <Markdown
              className="mr-6"
              components={{
                h1: ({ children }) => (
                  <h1 className="font-bold text-xl first-letter:uppercase first-of-type:mt-0 mt-6">
                    {children}
                  </h1>
                ),
                h2: ({ children }) => (
                  <h2 className="font-semibold mt-4 text-lg">{children}</h2>
                ),
                p: ({ children }) => <p className="mb-0.5">{children}</p>,
                ul: ({ children }) => (
                  <ul className="list-disc list-inside mb-2">{children}</ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal list-inside mb-2">{children}</ol>
                ),
              }}
            >
              {mardownFeedback}
            </Markdown>
          </ScrollArea>
        </section>
        <div className="mt-3 italic text-muted-foreground text-center text-xs">
          Feedback generated using ollama3 at 31/03/1994 23:04
        </div>
        <DialogFooter className="grid grid-cols-2">
          <Button variant="outline" disabled>
            <ArrowLeft />
            Previous disciplinary
          </Button>
          <Button disabled>
            Next disciplinary
            <ArrowRight />
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
